DROP TABLE IF EXISTS BOOKS;

CREATE SEQUENCE book_id_seq
START WITH 1
  INCREMENT BY 50
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE BOOK (
  id  BIGINT NOT NULL DEFAULT nextval('book_id_seq' :: REGCLASS),
  "title" VARCHAR(255)  NOT NULL,
  "description" VARCHAR(255) NOT NULL,
  CONSTRAINT BOOK_pk PRIMARY KEY ("id")
) WITH (
  OIDS = FALSE
);

CREATE SEQUENCE author_id_seq
START WITH 1
INCREMENT BY 50
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE AUTHOR (
  id  BIGINT NOT NULL DEFAULT nextval('author_id_seq' :: REGCLASS),
  "name" VARCHAR(255)  NOT NULL,
  "style" VARCHAR(255) NOT NULL,
  CONSTRAINT BOOK_pk PRIMARY KEY ("id")
) WITH (
OIDS = FALSE
);